max_width = 160
match_block_trailing_comma = true
merge_derives = false
use_field_init_shorthand = true
chain_width = 100
fn_call_width = 140

# TODO enable when stabilized
#condense_wildcard_suffixes = true
#wrap_comments = true
#imports_granularity = "Module"
#fn_single_line = true
#force_multiline_blocks = true
#format_generated_files = false
#reorder_impl_items = true
#struct_field_align_threshold = 20
